name: Create and publish a Docker image

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: euracresearch
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          build-args: |
            "browser_ref=${{ github.ref_name }}"
            "browser_sha=${{ github.sha }}"
          context: .
          push: true
          tags: ghcr.io/euracresearch/influx-proxy:${{ github.ref_name }}